# Generated by Django 3.1 on 2026-03-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reginfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=10)),
                ('standard', models.IntegerField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
