# Generated by Django 3.1 on 2026-03-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reginfo',
            name='age',
        ),
        migrations.RemoveField(
            model_name='reginfo',
            name='standard',
        ),
        migrations.AddField(
            model_name='reginfo',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
